### ISSUE TITLE
The saved pre-trained models are cracked? 

### ISSUE THREAD

**Issue by PanZiwei** [pepebonet/DeepMP#15]
To whom it may concern,
I am trying to load the pre-trained model or open the model with h5py, but I failed to load the model in both ways with the error `OSError: Unable to open file (file signature not found)`

Do you have an idea about the problem?  

Thank you so much for your time in advance!

```python
import h5py
trained_model = 'DeepMP/trained_models/NA12878_Norwich_joint_202106/saved_model.pb'

f= h5py.File(trained_model, 'r+')  ##Failed

model = load_model_weights(trained_model=trained_model, model_type=None, kmer=17) ##Failed
```

The error message is shown below:
```
File /Ziwei/Anaconda3/envs/deepmp_2021/lib/python3.8/site-packages/h5py/_hl/files.py:220, in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    218     if swmr and swmr_support:
    219         flags |= h5f.ACC_SWMR_READ
--> 220     fid = h5f.open(name, flags, fapl=fapl)
    221 elif mode == 'r+':
    222     fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5f.pyx:106, in h5py.h5f.open()

OSError: Unable to open file (file signature not found)
```

I checked the TensorFlow [save and load models](https://www.tensorflow.org/tutorials/keras/save_and_load) part and it seems that `keras_metadata.pb` and `assets` are missing? 
![Screen Shot 2022-03-15 at 1 47 18 PM](https://user-images.githubusercontent.com/44417006/158440196-f0eb8516-d8e2-47a1-8d4b-6cab74209b91.png)

**Comment by pepebonet** [comment]
Hi PanZiwei! 

Thank you for raising this issue. We were able to reproduce the error on our end. However, the trained models are loaded within DeepMP using the following: 

```
import tensorflow as tf
trained_model = 'DeepMP/trained_models/NA12878_Norwich_joint_202106'
my_model = tf.keras.models.load_model(trained_model)
```

We are sorry about the confusion with the function load_model_weights(), employing load_model_or_weights() should overcome this problem as call_modifications will first try to use load_model() from kears. Example: 

```
from deepmp.call_modifications import load_model_or_weights
trained_model = 'DeepMP/trained_models/NA12878_Norwich_joint_202106'
model = load_model_or_weights(model_file=trained_model, model_type=None, kmer=17)
```

We were able to load every trained model available on our end. Please let us know if this helps or whether we can do anything else for you. 

Best,
Pepe
