### ISSUE TITLE
R10 data dan other methylation context

### ISSUE THREAD

**Issue by yusmiatiliau** [pepebonet/DeepMP#16]
Dear DeepMP author,

May I know if this tool can be used to call methylation from data from R10 flowcells?
Also, is it restricted to CpG context or would it be able to call methylation from all other contexts (such as in plants).

Thank you

**Comment by pepebonet** [comment]
Thank you for the question. 

Although we did not use R10 flowcells for the publication and have not tried it, it should not be a problem to call methylation from such data.

The models we have trained are on CpG (5mC detection) and GATC (6mA detection) contexts. For CpG context the models we have trained are in Humans and E. Coli. For the GATC context, we used a pUC19 plasmid dataset. Ideally, these models could also be applied to other organisms such as plants for the detection of the same contexts. You can use them and they are available in the trained_models folder. 

On the other hand, if you want to call methylations from a new context (detection of methylation in Gs for instance), this is also possible. However, for this, you will need your own labeled data to train the model and then use it.  

I hope the answers help and let us know if there is anything else we can help with. 
Best, 

Pepe

**Comment by yusmiatiliau** [comment]
Dear Pepe,

Thank you for your answer.
