### ISSUE TITLE
Arabidopsis' model

### ISSUE THREAD

**Issue by Fadwa7** [pepebonet/DeepMP#19]
Hi , 
Thank you for this software. 
it's been a few days since i tried to work with your software. 
I'm working on arabidopsis thaliana , and i want to build a model. but i don't know how to split data? 
Can you please provide an example of training and validation data ? 

Thank you in Advance

Best Regards

**Comment by mandichen** [comment]
Hi Fadwa7,

At the **Preprocess** step, adding the `-sf` flag to`DeepMP preprocess`  should automatically split the data into train, validation and test sets.

Please let us know if this works for you.

Cheers,
Mandi

**Comment by Fadwa7** [comment]
Thank you , it works :)
